apiVersion: v1
kind: Namespace
metadata:
  name: observability-graph
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/part-of: observability-kit
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: observability-graph
  labels:
    app.kubernetes.io/name: neo4j
spec:
  serviceName: neo4j
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: neo4j
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:5.26
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          env:
            - name: NEO4J_AUTH
              value: "neo4j/replace-me"
            - name: NEO4J_server_default__listen__address
              value: "0.0.0.0"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
