"""Per-tenant GitOps overlay rendering through the Batch 19 renderer.

Implements contracts/tenancy/TENANT_OVERLAY_GENERATION_CONTRACT_V1.yaml
on top of the obskit.configrender library (ADR-0003/ADR-0004): overlay
contents are planned here as deterministic text parameterized ONLY by
validated tenant-descriptor fields, packaged into the renderer's
RenderPlan model, and written/diff-checked exclusively through the
renderer's execute_plan and changed_paths functions. The service never
mutates clusters or stores directly for persistent configuration
(TR-10) - a transition's side effects are rendered files plus a
prepared commit reference.

Overlays exist only for the dedicated-stack isolation class (lifecycle
contract outputs_by_isolation_class; the API contract's
render_action: not-applicable covers the other classes).

obskit is a logical dependency resolved in-repo: when the package is
not installed, tools/obskit is added to sys.path relative to this
file's position in the monorepo (services/tenancy/tenantctl/), the
same pattern the repo's offline tests use (see
services/tenancy/pyproject.toml).
"""

from __future__ import annotations

import hashlib
import json
import shutil
import sys
from pathlib import Path
from typing import Any, Mapping


def _ensure_obskit_importable() -> None:
    try:
        import obskit  # noqa: F401
        return
    except ModuleNotFoundError:
        pkg_root = (
            Path(__file__).resolve().parents[3] / "tools" / "obskit"
        )
        if not (pkg_root / "obskit" / "__init__.py").is_file():
            raise ModuleNotFoundError(
                "the obskit package is not installed and tools/obskit "
                "was not found relative to services/tenancy; install "
                "obskit or run from the repository checkout"
            ) from None
        sys.path.insert(0, str(pkg_root))


_ensure_obskit_importable()

from obskit.configrender.models import (  # noqa: E402
    PlannedArtifact,
    RenderPlan,
    STRATEGY_OWNED_ARTIFACT,
)
from obskit.configrender.render import (  # noqa: E402
    changed_paths,
    execute_plan,
)
from obskit.emit import canonical_json  # noqa: E402

# Header marker, verbatim from the overlay generation contract
# (generated_file_header_marker).
OVERLAY_MARKER = (
    "GENERATED by the tenant overlay generator - DO NOT EDIT BY HAND."
)
OVERLAY_MARKER_COMMENT = f"# {OVERLAY_MARKER}"

OVERLAY_ROOT = "gitops/overlays/tenants/"
TENANT_VALUES_FILENAME = "tenant-values.yaml"
APPSET_ELEMENT_FILENAME = "applicationset-element.yaml"

# Bookkeeping identifiers carried in PlannedArtifact/manifest entries.
# The strategy id is the renderer architecture contract's
# owned-artifact strategy: a generator-owned directory receives
# deterministic artifacts derived from validated input.
_SYSTEM = "tenant-delivery"
_KEY_TENANT_VALUES = "tenancy.overlay.tenant_values"
_KEY_APPSET_ELEMENT = "tenancy.overlay.applicationset_element"

OVERLAY_MANIFEST_SCHEMA_VERSION = "v1"


def overlay_dir(tenant_id: str) -> str:
    """Repo-relative overlay directory (trailing slash), named exactly
    after the descriptor tenant_id per the overlay contract."""
    return f"{OVERLAY_ROOT}{tenant_id}/"


def _sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _scalar(value: Any) -> str:
    # json.dumps renders YAML-compatible scalars deterministically:
    # numbers without locale drift, booleans lowercase, and free-text
    # strings double-quoted with escapes.
    return json.dumps(value)


def build_tenant_values(tenant: Mapping[str, Any]) -> str:
    """Render tenant-values.yaml from descriptor fields only.

    lifecycle_state is deliberately not emitted although the contract
    allows it as a parameter: suspend/offboard retain the overlay
    unchanged (no re-render), so any state-dependent byte would break
    the retained/idempotent-regeneration invariants.
    """
    residency = tenant["residency"]
    quotas = tenant["quotas"]
    ingest = quotas["ingest"]
    retention = quotas["retention"]
    lines = [
        OVERLAY_MARKER_COMMENT,
        "tenant:",
        f"  id: {tenant['tenant_id']}",
        f"  display_name: {_scalar(tenant['display_name'])}",
        f"  tier: {tenant['tier']}",
        f"  isolation_class: {tenant['isolation_class']}",
        "  residency:",
        f"    region: {_scalar(residency['region'])}",
        "    data_residency_required: "
        f"{_scalar(residency['data_residency_required'])}",
        f"    pool: {residency['pool']}",
        "  quotas:",
        "    ingest:",
        f"      max_gb_per_day: {_scalar(ingest['max_gb_per_day'])}",
    ]
    if "max_events_per_second" in ingest:
        lines.append(
            "      max_events_per_second: "
            f"{_scalar(ingest['max_events_per_second'])}"
        )
    lines.extend(
        [
            "    retention:",
            f"      logs_days: {_scalar(retention['logs_days'])}",
            f"      metrics_days: {_scalar(retention['metrics_days'])}",
            f"      traces_days: {_scalar(retention['traces_days'])}",
        ]
    )
    return "\n".join(lines) + "\n"


def build_appset_element(tenant: Mapping[str, Any]) -> str:
    """Render the flat ApplicationSet list-generator element.

    Environment-specific fields (destination server, repoURL,
    targetRevision) belong to the ApplicationSet template owned by the
    control plane and are forbidden here by the overlay contract.
    """
    residency = tenant["residency"]
    lines = [
        OVERLAY_MARKER_COMMENT,
        f"tenant_id: {tenant['tenant_id']}",
        f"display_name: {_scalar(tenant['display_name'])}",
        f"tier: {tenant['tier']}",
        f"isolation_class: {tenant['isolation_class']}",
        f"residency_region: {_scalar(residency['region'])}",
        f"residency_pool: {residency['pool']}",
        "data_residency_required: "
        f"{_scalar(residency['data_residency_required'])}",
    ]
    return "\n".join(lines) + "\n"


def _descriptor_digest(tenant: Mapping[str, Any]) -> str:
    # lifecycle_state is excluded, exactly like the rendered files
    # exclude it (see build_tenant_values): the overlay and its
    # manifest must be byte-stable across state changes that retain
    # the overlay, or every post-provision replay would look drifted.
    stable = {
        key: value
        for key, value in tenant.items()
        if key != "lifecycle_state"
    }
    canonical = canonical_json(stable).encode("utf-8")
    return f"sha256:{_sha256_hex(canonical)}"


def _render_commit_message(
    tenant_id: str, document_digest: str, artifact_count: int
) -> str:
    digest_hex = document_digest.removeprefix("sha256:")
    return (
        f"tenancy({tenant_id}): render tenant overlay "
        f"{digest_hex[:12]}\n"
        "\n"
        f"overlay {overlay_dir(tenant_id)}; files {artifact_count}\n"
        "\n"
        f"Tenant-Contract-Digest: {document_digest}\n"
        "Tenant-Overlay-Contract: "
        "contracts/tenancy/TENANT_OVERLAY_GENERATION_CONTRACT_V1.yaml\n"
    )


def removal_commit_message(tenant_id: str) -> str:
    return (
        f"tenancy({tenant_id}): remove tenant overlay (purge)\n"
        "\n"
        f"overlay {overlay_dir(tenant_id)} removed via git commit per "
        "purged_behavior\n"
        "\n"
        "Tenant-Overlay-Contract: "
        "contracts/tenancy/TENANT_OVERLAY_GENERATION_CONTRACT_V1.yaml\n"
    )


def plan_overlay_render(
    tenant: Mapping[str, Any],
    manifest_path: Path,
) -> RenderPlan:
    """Plan the per-tenant overlay as a Batch 19 RenderPlan.

    The plan is executed with obskit.configrender.render.execute_plan
    and diff-checked with changed_paths, giving tenant overlays the
    renderer's determinism and idempotency semantics for free. The
    render manifest is a control-plane record (manifest_path lives in
    the control-plane store, not the git tree), keeping the overlay
    directory to exactly the contract's two required files.
    """
    tenant_id = tenant["tenant_id"]
    directory = overlay_dir(tenant_id)
    artifacts = (
        PlannedArtifact(
            path=f"{directory}{APPSET_ELEMENT_FILENAME}",
            content=build_appset_element(tenant),
            strategy=STRATEGY_OWNED_ARTIFACT,
            unified_key=_KEY_APPSET_ELEMENT,
            system=_SYSTEM,
        ),
        PlannedArtifact(
            path=f"{directory}{TENANT_VALUES_FILENAME}",
            content=build_tenant_values(tenant),
            strategy=STRATEGY_OWNED_ARTIFACT,
            unified_key=_KEY_TENANT_VALUES,
            system=_SYSTEM,
        ),
    )
    document_digest = _descriptor_digest(tenant)
    manifest_content = canonical_json(
        {
            "schema_version": OVERLAY_MANIFEST_SCHEMA_VERSION,
            "document_digest": document_digest,
            "marker": OVERLAY_MARKER,
            "artifacts": [
                {
                    "path": artifact.path,
                    "sha256": _sha256_hex(
                        artifact.content.encode("utf-8")
                    ),
                    "strategy": artifact.strategy,
                    "system": artifact.system,
                    "unified_key": artifact.unified_key,
                }
                for artifact in artifacts
            ],
            "skipped": [],
            "recorded": [],
        }
    )
    return RenderPlan(
        schema_version=OVERLAY_MANIFEST_SCHEMA_VERSION,
        document_digest=document_digest,
        artifacts=artifacts,
        skipped=(),
        recorded=(),
        manifest_path=str(manifest_path),
        manifest_content=manifest_content,
        commit_message=_render_commit_message(
            tenant_id, document_digest, len(artifacts)
        ),
    )


def overlay_changed(
    plan: RenderPlan, repo_root: Path
) -> tuple[str, ...]:
    """Paths the plan would change (Batch 19 changed_paths)."""
    return changed_paths(plan, repo_root)


def execute_overlay_render(
    plan: RenderPlan, repo_root: Path
) -> tuple[str, ...]:
    """Write the overlay through the Batch 19 renderer."""
    return execute_plan(plan, repo_root)


def commit_ref_for(plan: RenderPlan) -> str:
    """Opaque prepared-commit reference for a rendered overlay.

    Deterministic: derived from the descriptor digest, mirroring how
    the Batch 19 commit trailers bind a propagation commit to its
    document revision. No git command runs here.
    """
    return f"prepared:{plan.document_digest}"


def remove_overlay(repo_root: Path, tenant_id: str) -> bool:
    """Remove the tenant overlay directory (purge, delete-if-present).

    Returns True when a directory was removed, False when it was
    already absent (idempotent replay / partially completed purge).
    """
    directory = (repo_root / OVERLAY_ROOT / tenant_id).resolve()
    root = (repo_root / OVERLAY_ROOT).resolve()
    # Containment guard mirroring the renderer's write-scope checks:
    # tenant_id is schema-validated, but never trust a path segment.
    if root not in directory.parents:
        raise ValueError(
            f"overlay directory for {tenant_id!r} escapes "
            f"{OVERLAY_ROOT}; refusing to remove"
        )
    if not directory.is_dir():
        return False
    shutil.rmtree(directory)
    return True
