{{- if and .Values.collector.enabled .Values.collector.agent.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-agent
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: otel-agent
  template:
    metadata:
      labels:
        app: otel-agent
    spec:
      containers:
        - name: otel-agent
          image: "{{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}"
          args:
            - "--config=/conf/collector-agent.yaml"
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 10
            periodSeconds: 15
{{- end }}
