"""Shared dataclasses and constants for the guided installer.

This module is the interface between the installer's step modules
(wizard, contract, render, finalize, flow) and is owned by the flow
contract: the step ids below mirror
contracts/install/INSTALL_FLOW_CONTRACT_V1.yaml, and flow.py asserts
the sequence against the contract at runtime so order drift fails
loudly (ADR-0002).

Stdlib-only and frozen-dataclass typed, per ADR-0001/ADR-0002.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

# Step ids, in the exact order INSTALL_FLOW_CONTRACT_V1.yaml fixes.
STEP_PREFLIGHT = "preflight"
STEP_GRADING = "grading"
STEP_MODE_RECOMMENDATION = "mode-recommendation"
STEP_CONTRACT_CAPTURE = "contract-capture"
STEP_RENDER = "render"
STEP_ARGOCD_BOOTSTRAP = "argocd-bootstrap"
STEP_READINESS = "post-install-readiness"

STEP_ORDER: tuple[str, ...] = (
    STEP_PREFLIGHT,
    STEP_GRADING,
    STEP_MODE_RECOMMENDATION,
    STEP_CONTRACT_CAPTURE,
    STEP_RENDER,
    STEP_ARGOCD_BOOTSTRAP,
    STEP_READINESS,
)

# Artifact filenames within the install output directory.
ANSWERS_FILENAME = "answers.json"
INSTALL_CONTRACT_FILENAME = "install_contract.json"
INSTALL_STATE_FILENAME = "install_state.json"
INSTALL_SUMMARY_FILENAME = "install_summary.json"
RENDERED_DIRNAME = "rendered"

# Generated-file header marker carried by every rendered file. Mirrors
# the propagation contract's marker convention (a fixed first-line
# marker makes hand edits detectable); the wording names this tool
# because the guided installer, not the unified configuration
# renderer, is the writer.
GENERATED_FILE_HEADER = (
    "GENERATED by the Observability Kit guided installer"
    " - DO NOT EDIT BY HAND."
)

# Step statuses recorded in the install_state.json journal.
STATUS_COMPLETED = "completed"
STATUS_FAILED = "failed"
STATUS_SKIPPED = "skipped"


class InstallFlowError(RuntimeError):
    """Raised for contract violations and unrecoverable flow errors."""


@dataclass(frozen=True)
class AttachedServices:
    """Existing-service endpoints for attach and hybrid modes."""

    opensearch_endpoint: str | None = None
    dashboards_endpoint: str | None = None
    otlp_endpoint: str | None = None

    def to_mapping(self) -> dict[str, str]:
        return {
            key: value
            for key, value in (
                ("opensearch_endpoint", self.opensearch_endpoint),
                ("dashboards_endpoint", self.dashboards_endpoint),
                ("otlp_endpoint", self.otlp_endpoint),
            )
            if value is not None
        }


@dataclass(frozen=True)
class ExternalTrustReferences:
    """References to externally managed trust material."""

    secret_ref: str | None = None
    pki_ref: str | None = None
    identity_provider_ref: str | None = None

    def to_mapping(self) -> dict[str, str]:
        return {
            key: value
            for key, value in (
                ("secret_ref", self.secret_ref),
                ("pki_ref", self.pki_ref),
                ("identity_provider_ref", self.identity_provider_ref),
            )
            if value is not None
        }


@dataclass(frozen=True)
class InstallAnswers:
    """The install contract answers, one field per schema property.

    The mapping form (to_mapping / from_mapping) is what validates
    against contracts/install/INSTALL_CONTRACT_SCHEMA.json and what
    lands in answers.json and install_contract.json.
    """

    cluster_name: str
    environment: str
    deployment_mode: str
    gitops_repo_url: str
    gitops_path: str
    base_domain: str
    storage_profile: str
    object_storage_profile: str
    identity_profile: str
    secret_profile: str
    ingress_profile: str
    attached_services: AttachedServices | None = None
    external_trust_references: ExternalTrustReferences | None = None

    def to_mapping(self) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "cluster_name": self.cluster_name,
            "environment": self.environment,
            "deployment_mode": self.deployment_mode,
            "gitops_repo_url": self.gitops_repo_url,
            "gitops_path": self.gitops_path,
            "base_domain": self.base_domain,
            "storage_profile": self.storage_profile,
            "object_storage_profile": self.object_storage_profile,
            "identity_profile": self.identity_profile,
            "secret_profile": self.secret_profile,
            "ingress_profile": self.ingress_profile,
        }
        if self.attached_services is not None:
            payload["attached_services"] = (
                self.attached_services.to_mapping()
            )
        if self.external_trust_references is not None:
            payload["external_trust_references"] = (
                self.external_trust_references.to_mapping()
            )
        return payload

    @staticmethod
    def from_mapping(payload: dict[str, Any]) -> "InstallAnswers":
        attached = payload.get("attached_services")
        trust = payload.get("external_trust_references")
        return InstallAnswers(
            cluster_name=payload["cluster_name"],
            environment=payload["environment"],
            deployment_mode=payload["deployment_mode"],
            gitops_repo_url=payload["gitops_repo_url"],
            gitops_path=payload["gitops_path"],
            base_domain=payload["base_domain"],
            storage_profile=payload["storage_profile"],
            object_storage_profile=payload["object_storage_profile"],
            identity_profile=payload["identity_profile"],
            secret_profile=payload["secret_profile"],
            ingress_profile=payload["ingress_profile"],
            attached_services=(
                AttachedServices(**attached)
                if isinstance(attached, dict)
                else None
            ),
            external_trust_references=(
                ExternalTrustReferences(**trust)
                if isinstance(trust, dict)
                else None
            ),
        )


@dataclass(frozen=True)
class StepResult:
    """Outcome of one flow step execution."""

    step_id: str
    status: str
    outputs: tuple[str, ...] = ()
    detail: str = ""


@dataclass(frozen=True)
class RenderResult:
    """Files written by the render or bootstrap step.

    Paths are relative to the install output directory so results are
    stable across output locations (determinism, ADR-0002).
    """

    files: tuple[str, ...]


@dataclass
class InstallState:
    """The install_state.json journal: per-step status and digests.

    The one deliberately mutable artifact of the flow. steps maps a
    step id to a record with keys: status, input_digest, outputs.
    """

    steps: dict[str, dict[str, Any]] = field(default_factory=dict)

    def to_mapping(self) -> dict[str, Any]:
        return {"steps": self.steps}

    @staticmethod
    def from_mapping(payload: dict[str, Any]) -> "InstallState":
        steps = payload.get("steps", {})
        if not isinstance(steps, dict):
            raise InstallFlowError(
                "install_state.json: 'steps' must be an object"
            )
        return InstallState(steps=steps)
