"""Shared constants and frozen dataclasses for the config renderer.

This module is the interface between the renderer's stages (document
loading, contract fact extraction, strategy patching, planning,
emission) and pins the values fixed by
contracts/management/PROPAGATION_RECONCILIATION_CONTRACT_V1.yaml and
contracts/management/RENDERER_ARCHITECTURE_CONTRACT_V1.yaml: the
generated-file header marker, the render manifest path and schema
version, and the required commit trailers (ADR-0003, TR-20).

Stdlib-only and frozen-dataclass typed, per ADR-0001/ADR-0003.
"""

from __future__ import annotations

from dataclasses import dataclass

# Generated-file header marker, exactly as the propagation contract's
# generated_file_header_marker fixes it. YAML targets carry it as a
# leading comment line; comment-incapable formats (JSON, NDJSON) carry
# it through the render manifest (header_marker_notes).
MARKER = (
    "GENERATED by the unified configuration renderer"
    " - DO NOT EDIT BY HAND."
)
MARKER_COMMENT = f"# {MARKER}"

# Render manifest location under the repo root and its format version
# (renderer architecture contract, outputs.render_manifest).
DEFAULT_MANIFEST_RELPATH = "gitops/UNIFIED_CONFIG_RENDER_MANIFEST.json"
MANIFEST_SCHEMA_VERSION = "v1"

# Required commit trailers binding a propagation commit back to the
# unified document revision that produced it (propagation contract,
# required_commit_trailers).
TRAILER_SCHEMA_VERSION = "Unified-Config-Schema-Version"
TRAILER_DOCUMENT_DIGEST = "Unified-Config-Document-Digest"

# The propagation contract's read-only path: the renderer must never
# write under the upstream-owned charts tree.
FORBIDDEN_WRITE_PREFIX = "gitops/charts/"

# Exit codes of `obskit render`: 0 success / no diff, 2 operator error
# (validation, cross-file rule, or unsupported structure - nothing
# written), 3 --check found targets that would change.
EXIT_OK = 0
EXIT_ERROR = 2
EXIT_CHECK_CHANGED = 3

# Strategy ids, exactly as cataloged in
# RENDERER_ARCHITECTURE_CONTRACT_V1.yaml render_strategies.catalog.
STRATEGY_JSON_PATH_PATCH = "json-path-patch"
STRATEGY_YAML_LINE_PATCH = "yaml-line-patch"
STRATEGY_OWNED_ARTIFACT = "owned-artifact"
STRATEGY_PRESENCE_GATED = "presence-gated"


class ConfigRenderError(RuntimeError):
    """Raised for contract violations and unrenderable inputs.

    Every raise happens before any file is written: the renderer plans
    fully in memory, so a failing render leaves the tree untouched.
    """


@dataclass(frozen=True)
class Binding:
    """One propagation binding from the unified document."""

    unified_key: str
    system: str
    repo_path: str
    locator: str
    render_target: str


@dataclass(frozen=True)
class StrategyEntry:
    """One render_strategies.bindings catalog entry."""

    unified_key: str
    system: str
    strategy: str
    value_transform: str


@dataclass(frozen=True)
class RegistryFacts:
    """System ids and config-surface paths from the wrapped-system
    registry, extracted line-based (stdlib-only)."""

    systems: tuple[str, ...]
    # (system id, surface path); directory surfaces end with "/".
    config_surfaces: tuple[tuple[str, str], ...]

    def surfaces_for(self, system: str) -> tuple[str, ...]:
        return tuple(
            path
            for owner, path in self.config_surfaces
            if owner == system
        )


@dataclass(frozen=True)
class PlannedArtifact:
    """One (rendered file, contributing binding) pair of the plan.

    Several bindings may patch the same file; each contributes one
    manifest entry, all carrying the file's final content digest.
    """

    path: str
    content: str
    strategy: str
    unified_key: str
    system: str


@dataclass(frozen=True)
class SkippedTarget:
    """A presence-gated target deliberately not rendered."""

    path: str
    unified_key: str
    system: str
    strategy: str
    reason: str


@dataclass(frozen=True)
class RecordedFile:
    """A pre-existing file in an owned-artifact directory, recorded by
    digest in the manifest and never rewritten."""

    path: str
    sha256: str


@dataclass(frozen=True)
class RenderPlan:
    """The complete in-memory result of planning one render.

    manifest_path is the absolute filesystem path the manifest lands
    at; every artifact path is repository-relative (POSIX separators).
    """

    schema_version: str
    document_digest: str
    artifacts: tuple[PlannedArtifact, ...]
    skipped: tuple[SkippedTarget, ...]
    recorded: tuple[RecordedFile, ...]
    manifest_path: str
    manifest_content: str
    commit_message: str

    def unique_artifact_paths(self) -> tuple[str, ...]:
        seen: dict[str, None] = {}
        for artifact in self.artifacts:
            seen.setdefault(artifact.path, None)
        return tuple(seen)
