#!/usr/bin/env python3
"""Deterministic API reference generator (Batch 26 Task 3, TR-26).

Reads contracts/tenancy/TENANT_CONTROL_PLANE_API_V1.yaml (the TR-21
OpenAPI contract) and renders docs/product/API_REFERENCE.md. The
rendering is a pure function of the contract file: paths, operations,
components, and vendor extensions are emitted in contract document
order, no timestamps or environment data are embedded, and running the
generator twice produces byte-identical output.

The output carries a generated-file header marker (HTML comment) in the
same spirit as the Batch 15/19 generated-file header conventions
(TENANT_OVERLAY_GENERATION_CONTRACT_V1.yaml generated_file_header_marker
and the config renderer's marker in tools/obskit/obskit/configrender/
models.py). Hand edits are detected by --check: it regenerates to
memory and exits non-zero when the committed file differs, which is how
the Batch 26 validator turns hand-written drift into a validation
failure (TR-26).

Usage:
    generate_api_reference.py            # write the reference
    generate_api_reference.py --check    # verify, never write

Requires PyYAML (available in the repo venv created by
scripts/ci/setup_python_env.sh).
"""

from __future__ import annotations

import argparse
import re
import sys
import textwrap
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
CONTRACT_RELPATH = "contracts/tenancy/TENANT_CONTROL_PLANE_API_V1.yaml"
OUTPUT_RELPATH = "docs/product/API_REFERENCE.md"

# Generated-file marker, following the repository convention fixed by
# TENANT_OVERLAY_GENERATION_CONTRACT_V1.yaml (generated_file_header_marker)
# and the config renderer (ADR-0003). Markdown cannot carry a comment
# line the way YAML does, so the marker is an HTML comment.
MARKER_LINES = (
    "<!--",
    "GENERATED by scripts/dev/generate_api_reference.py from",
    "contracts/tenancy/TENANT_CONTROL_PLANE_API_V1.yaml"
    " - DO NOT EDIT BY HAND.",
    "Hand edits are a validation failure (TR-26); edit the contract and",
    "re-run the generator.",
    "-->",
)

WIDTH = 80


def norm(text: Any) -> str:
    """Collapse a YAML scalar into one whitespace-normalized string."""
    if text is None:
        return ""
    return re.sub(r"\s+", " ", str(text)).strip()


_HTML_LIKE_TOKEN = re.compile(r"<[A-Za-z][A-Za-z0-9-]*>")
_TRAILING_PUNCT = re.compile(r"([.,;:!?)]*)$")


def guard_html_tokens(text: str) -> str:
    """Backtick tokens like <name> so they never lint as inline HTML.

    Placeholder tokens whose inner word is a valid HTML tag name (for
    example <name>) would otherwise be parsed as inline HTML (MD033).
    Tokens already carrying backticks are left untouched.
    """
    out: list[str] = []
    for token in text.split(" "):
        if "`" not in token and _HTML_LIKE_TOKEN.search(token):
            match = _TRAILING_PUNCT.search(token)
            punct = match.group(1) if match else ""
            core = token[: len(token) - len(punct)] if punct else token
            token = f"`{core}`{punct}"
        out.append(token)
    return " ".join(out)


def wrap(text: Any, indent: str = "") -> list[str]:
    """Wrap prose to the repository's 80-column standard."""
    body = guard_html_tokens(norm(text))
    if not body:
        return []
    # Glue a standalone list-marker-looking token ("-", "*", "+") to the
    # word before it so a wrapped continuation line can never begin with
    # a list marker (MD032). The NUL placeholder is restored to a space
    # after wrapping; widths are unchanged because both are one char.
    body = re.sub(r" ([-*+]) ", lambda m: "\x00" + m.group(1) + " ", body)
    wrapped = textwrap.wrap(
        body,
        width=WIDTH,
        initial_indent=indent,
        subsequent_indent=indent,
        break_long_words=False,
        break_on_hyphens=False,
    )
    return [line.replace("\x00", " ") for line in wrapped]


def cell(text: Any) -> str:
    """Make a value safe inside a markdown table cell."""
    return guard_html_tokens(norm(text)).replace("|", "\\|")


def ref_name(ref: str) -> str:
    """Last segment of a JSON pointer reference."""
    return ref.rsplit("/", 1)[-1]


def type_str(schema: dict[str, Any] | None) -> str:
    """Human-readable type for a JSON-schema node."""
    if not isinstance(schema, dict):
        return ""
    if "$ref" in schema:
        return f"`{ref_name(schema['$ref'])}`"
    stype = schema.get("type")
    if stype == "array":
        items = schema.get("items")
        inner = type_str(items) if isinstance(items, dict) else "any"
        return f"array of {inner}"
    for combiner in ("oneOf", "anyOf", "allOf"):
        if combiner in schema:
            parts = ", ".join(
                type_str(s) for s in schema[combiner] if isinstance(s, dict)
            )
            return f"{combiner}: {parts}"
    if isinstance(stype, str):
        if schema.get("enum"):
            return f"{stype} (enum)"
        return stype
    return "any"


def constraint_str(schema: dict[str, Any]) -> str:
    """Render the constraint keywords of a JSON-schema node."""
    parts: list[str] = []
    if "enum" in schema:
        values = ", ".join(f"`{v}`" for v in schema["enum"])
        parts.append(f"one of {values}")
    if "pattern" in schema:
        parts.append(f"pattern `{schema['pattern']}`")
    if "format" in schema:
        parts.append(f"format `{schema['format']}`")
    for key, label in (
        ("minimum", "minimum"),
        ("maximum", "maximum"),
        ("exclusiveMinimum", "exclusive minimum"),
        ("exclusiveMaximum", "exclusive maximum"),
        ("minLength", "min length"),
        ("maxLength", "max length"),
        ("minItems", "min items"),
        ("maxItems", "max items"),
    ):
        if key in schema:
            parts.append(f"{label} {schema[key]}")
    if schema.get("additionalProperties") is False:
        parts.append("no additional properties")
    if "const" in schema:
        parts.append(f"constant `{schema['const']}`")
    if "default" in schema:
        parts.append(f"default `{schema['default']}`")
    return "; ".join(parts)


def property_rows(schema: dict[str, Any], prefix: str = "") -> list[str]:
    """Flatten a JSON-schema object into dotted-path table rows."""
    rows: list[str] = []
    required = set(schema.get("required") or [])
    for name, sub in (schema.get("properties") or {}).items():
        if not isinstance(sub, dict):
            continue
        path = f"{prefix}{name}"
        req = "yes" if name in required else "no"
        rows.append(
            f"| `{path}` | {cell(type_str(sub))} | {req} "
            f"| {cell(constraint_str(sub))} "
            f"| {cell(sub.get('description'))} |"
        )
        if sub.get("type") == "object" and sub.get("properties"):
            rows.extend(property_rows(sub, f"{path}."))
        items = sub.get("items")
        if (
            sub.get("type") == "array"
            and isinstance(items, dict)
            and items.get("properties")
        ):
            rows.extend(property_rows(items, f"{path}[]."))
    return rows


def response_schema_name(response: dict[str, Any]) -> str:
    """Schema reference carried by a response object, if any."""
    content = response.get("content") or {}
    for media in content.values():
        schema = media.get("schema")
        if isinstance(schema, dict):
            return type_str(schema)
    return ""


class Renderer:
    """Renders the loaded contract into markdown lines."""

    def __init__(self, contract: dict[str, Any]) -> None:
        self.contract = contract
        self.components: dict[str, Any] = contract.get("components") or {}
        self.lines: list[str] = []

    def emit(self, *lines: str) -> None:
        self.lines.extend(lines)

    def blank(self) -> None:
        if self.lines and self.lines[-1] != "":
            self.lines.append("")

    def resolve(self, ref: str) -> Any:
        node: Any = self.contract
        for part in ref.lstrip("#/").split("/"):
            node = node[part]
        return node

    # -- document sections -------------------------------------------------

    def render(self) -> str:
        self.emit("# Tenant Control Plane API Reference")
        self.blank()
        self.emit(*MARKER_LINES)
        self.blank()
        toc_at = len(self.lines)
        self.section_overview()
        self.section_contract_metadata()
        self.section_servers()
        self.section_authentication()
        self.section_lifecycle_binding()
        self.section_endpoints()
        self.section_parameters()
        self.section_error_responses()
        self.section_schemas()
        self.insert_toc(toc_at)
        self.blank()
        return "\n".join(self.lines).rstrip("\n") + "\n"

    def insert_toc(self, position: int) -> None:
        """Insert a table of contents of the level-two sections.

        The repository markdown standard requires a TOC for documents
        over 200 lines. Built from the already-rendered headings, so it
        is exactly as deterministic as the sections themselves.
        """
        toc: list[str] = ["## Table of Contents", ""]
        for line in self.lines[position:]:
            if line.startswith("## "):
                title = line[3:].strip()
                # GitHub slugification keeps word characters including
                # underscores; only punctuation is dropped.
                anchor = re.sub(r"[^\w\- ]", "", title.lower())
                anchor = anchor.replace(" ", "-")
                toc.append(f"- [{title}](#{anchor})")
        toc.append("")
        self.lines[position:position] = toc

    def section_overview(self) -> None:
        info = self.contract.get("info") or {}
        self.emit("## Overview")
        self.blank()
        self.emit(
            f"API: {norm(info.get('title'))}, version"
            f" {norm(info.get('version'))} (OpenAPI"
            f" {norm(self.contract.get('openapi'))})."
        )
        self.blank()
        self.emit(*wrap(info.get("description")))
        self.blank()

    def section_contract_metadata(self) -> None:
        xc = self.contract.get("x-contract") or {}
        self.emit("## Contract Metadata")
        self.blank()
        self.emit("| Field | Value |")
        self.emit("| ---- | ---- |")
        self.emit(f"| Contract | `{cell(xc.get('contract'))}` |")
        self.emit(f"| Contract version | `{cell(xc.get('version'))}` |")
        self.emit(f"| Batch | `{cell(xc.get('batch'))}` |")
        markers = ", ".join(
            f"`{m}`" for m in (xc.get("requirement_markers") or [])
        )
        self.emit(f"| Requirement markers | {markers} |")
        self.emit(f"| ADR | `{cell(xc.get('adr'))}` |")
        self.emit("")
        related = xc.get("related_contracts") or {}
        if related:
            self.emit("Related contracts:")
            self.blank()
            for key, path in related.items():
                self.emit(f"- `{norm(key)}`: `{norm(path)}`")
            self.blank()

    def section_servers(self) -> None:
        servers = self.contract.get("servers") or []
        if not servers:
            return
        self.emit("## Servers")
        self.blank()
        self.emit("| URL | Description |")
        self.emit("| ---- | ---- |")
        for server in servers:
            self.emit(
                f"| `{cell(server.get('url'))}` "
                f"| {cell(server.get('description'))} |"
            )
        self.blank()

    def section_authentication(self) -> None:
        schemes = self.components.get("securitySchemes") or {}
        if not schemes:
            return
        self.emit("## Authentication and Caller Scope")
        self.blank()
        applied = [
            ", ".join(f"`{name}`" for name in entry)
            for entry in (self.contract.get("security") or [])
            if isinstance(entry, dict)
        ]
        if applied:
            self.emit(
                "Global security requirement: " + "; ".join(applied) + "."
            )
            self.blank()
        for name, scheme in schemes.items():
            scheme_type = norm(scheme.get("type"))
            scheme_kind = norm(scheme.get("scheme"))
            summary = f"`{name}` ({scheme_type}"
            if scheme_kind:
                summary += f", {scheme_kind}"
            summary += ")."
            self.emit(summary)
            self.blank()
            self.emit(*wrap(scheme.get("description")))
            self.blank()

    def section_lifecycle_binding(self) -> None:
        binding = self.contract.get("x-lifecycle-binding") or {}
        if not binding:
            return
        self.emit("## Lifecycle Binding")
        self.blank()
        self.emit(*wrap(
            "Lifecycle operations execute the state machine of"
            f" `{norm(binding.get('contract'))}` verbatim. The states,"
            " transitions, and gates below are that contract's facts as"
            " this API binds them."
        ))
        self.blank()
        states = ", ".join(f"`{s}`" for s in (binding.get("states") or []))
        terminal = ", ".join(
            f"`{s}`" for s in (binding.get("terminal_states") or [])
        )
        self.emit(f"- States: {states}")
        self.emit(f"- Initial state: `{norm(binding.get('initial_state'))}`")
        self.emit(f"- Terminal states: {terminal}")
        gitops_only = binding.get("gitops_only_transitions")
        self.emit(f"- GitOps-only transitions: `{str(gitops_only).lower()}`")
        self.blank()
        transitions = binding.get("transitions") or {}
        if transitions:
            self.emit("### Transitions")
            self.blank()
            self.emit(
                "| Transition | From | To | Operation | Destructive "
                "| Approval | Idempotent | Required audit fields |"
            )
            self.emit(
                "| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |"
            )
            for name, spec in transitions.items():
                frm = ", ".join(f"`{s}`" for s in (spec.get("from") or []))
                approval = spec.get("approval")
                if isinstance(approval, dict):
                    approval_text = (
                        f"`{norm(approval.get('risk_class'))}` per"
                        f" `{norm(approval.get('contract'))}`"
                    )
                else:
                    approval_text = "none"
                audit = ", ".join(
                    f"`{f}`"
                    for f in (spec.get("audit_required_fields") or [])
                )
                self.emit(
                    f"| `{name}` | {frm} | `{norm(spec.get('to'))}` "
                    f"| `{norm(spec.get('operation'))}` "
                    f"| {str(spec.get('destructive')).lower()} "
                    f"| {approval_text} "
                    f"| {str(spec.get('idempotent')).lower()} "
                    f"| {audit} |"
                )
            self.blank()
        replay = binding.get("idempotent_replay") or {}
        if replay:
            self.emit("### Idempotent Replay")
            self.blank()
            for key, value in replay.items():
                if isinstance(value, (bool, int, float, str)):
                    self.emit(f"- `{key}`: `{str(value).lower()}`")
                else:
                    self.emit(f"- `{key}`: {norm(value)}")
            self.blank()
        gates = binding.get("execution_gates") or {}
        if gates:
            self.emit("### Execution Gates")
            self.blank()
            for key, value in gates.items():
                self.emit(f"- `{key}`: `{str(value).lower()}`")
            self.blank()

    def section_endpoints(self) -> None:
        paths = self.contract.get("paths") or {}
        if not paths:
            return
        self.emit("## Endpoints")
        self.blank()
        tags = {
            norm(t.get("name")): norm(t.get("description"))
            for t in (self.contract.get("tags") or [])
        }
        if tags:
            self.emit("Operations are grouped by tag:")
            self.blank()
            for name, description in tags.items():
                self.emit(f"- `{name}`: {description}")
            self.blank()
        for path, item in paths.items():
            path_params = item.get("parameters") or []
            for method in (
                "get", "put", "post", "delete", "options", "head",
                "patch", "trace",
            ):
                operation = item.get(method)
                if not isinstance(operation, dict):
                    continue
                self.render_operation(path, method, operation, path_params)

    def render_operation(
        self,
        path: str,
        method: str,
        operation: dict[str, Any],
        path_params: list[Any],
    ) -> None:
        self.emit(f"### {method.upper()} {path}")
        self.blank()
        op_id = norm(operation.get("operationId"))
        op_tags = ", ".join(
            f"`{t}`" for t in (operation.get("tags") or [])
        )
        meta = f"Operation: `{op_id}`"
        if op_tags:
            meta += f". Tags: {op_tags}."
        self.emit(meta)
        self.blank()
        summary = norm(operation.get("summary"))
        if summary:
            self.emit(*wrap(summary))
            self.blank()
        description = norm(operation.get("description"))
        if description and description != summary:
            self.emit(*wrap(description))
            self.blank()
        params = list(path_params) + list(operation.get("parameters") or [])
        if params:
            self.emit("**Parameters:**")
            self.blank()
            self.emit("| Name | In | Required | Type | Description |")
            self.emit("| ---- | ---- | ---- | ---- | ---- |")
            for param in params:
                if isinstance(param, dict) and "$ref" in param:
                    param = self.resolve(param["$ref"])
                schema = param.get("schema") or {}
                required = "yes" if param.get("required") else "no"
                type_and_constraints = cell(type_str(schema))
                constraints = constraint_str(schema)
                if constraints:
                    type_and_constraints += f"; {cell(constraints)}"
                self.emit(
                    f"| `{cell(param.get('name'))}` "
                    f"| {cell(param.get('in'))} | {required} "
                    f"| {type_and_constraints} "
                    f"| {cell(param.get('description'))} |"
                )
            self.blank()
        body = operation.get("requestBody")
        if isinstance(body, dict):
            self.render_request_body(body)
        responses = operation.get("responses") or {}
        if responses:
            self.emit("**Responses:**")
            self.blank()
            self.emit("| Status | Description | Body |")
            self.emit("| ---- | ---- | ---- |")
            for status, response in responses.items():
                if isinstance(response, dict) and "$ref" in response:
                    name = ref_name(response["$ref"])
                    resolved = self.resolve(response["$ref"])
                    description = (
                        f"{norm(resolved.get('description'))}"
                        f" (shared response `{name}`)"
                    )
                    schema_name = response_schema_name(resolved)
                else:
                    description = norm(response.get("description"))
                    schema_name = response_schema_name(response)
                self.emit(
                    f"| `{status}` | {cell(description)} "
                    f"| {cell(schema_name)} |"
                )
            self.blank()

    def render_request_body(self, body: dict[str, Any]) -> None:
        if "$ref" in body:
            body = self.resolve(body["$ref"])
        required = "required" if body.get("required") else "optional"
        content = body.get("content") or {}
        for media_type, media in content.items():
            schema = media.get("schema")
            self.emit(
                f"**Request body** ({required}, `{media_type}`):"
                f" {type_str(schema) if isinstance(schema, dict) else 'any'}"
            )
            self.blank()
            body_description = norm(body.get("description"))
            if body_description:
                self.emit(*wrap(body_description))
                self.blank()
            if (
                isinstance(schema, dict)
                and "$ref" not in schema
                and schema.get("properties")
            ):
                self.emit(
                    "| Field | Type | Required | Constraints "
                    "| Description |"
                )
                self.emit("| ---- | ---- | ---- | ---- | ---- |")
                self.emit(*property_rows(schema))
                self.blank()

    def section_parameters(self) -> None:
        params = self.components.get("parameters") or {}
        if not params:
            return
        self.emit("## Shared Parameters")
        self.blank()
        self.emit(
            "| Component | Name | In | Required | Type | Description |"
        )
        self.emit("| ---- | ---- | ---- | ---- | ---- | ---- |")
        for comp_name, param in params.items():
            schema = param.get("schema") or {}
            required = "yes" if param.get("required") else "no"
            type_and_constraints = cell(type_str(schema))
            constraints = constraint_str(schema)
            if constraints:
                type_and_constraints += f"; {cell(constraints)}"
            self.emit(
                f"| `{comp_name}` | `{cell(param.get('name'))}` "
                f"| {cell(param.get('in'))} | {required} "
                f"| {type_and_constraints} "
                f"| {cell(param.get('description'))} |"
            )
        self.blank()

    def section_error_responses(self) -> None:
        responses = self.components.get("responses") or {}
        if not responses:
            return
        self.emit("## Shared Responses")
        self.blank()
        self.emit("| Response | Description | Body |")
        self.emit("| ---- | ---- | ---- |")
        for name, response in responses.items():
            self.emit(
                f"| `{name}` | {cell(response.get('description'))} "
                f"| {cell(response_schema_name(response))} |"
            )
        self.blank()

    def section_schemas(self) -> None:
        schemas = self.components.get("schemas") or {}
        if not schemas:
            return
        self.emit("## Schemas")
        self.blank()
        for name, schema in schemas.items():
            self.emit(f"### {name}")
            self.blank()
            description = norm(schema.get("description"))
            if description:
                self.emit(*wrap(description))
                self.blank()
            summary_bits: list[str] = []
            stype = type_str(schema)
            if stype:
                summary_bits.append(f"Type: {stype}")
            constraints = constraint_str(schema)
            if constraints:
                summary_bits.append(constraints)
            if summary_bits:
                self.emit(*wrap("; ".join(summary_bits) + "."))
                self.blank()
            if schema.get("properties"):
                self.emit(
                    "| Field | Type | Required | Constraints "
                    "| Description |"
                )
                self.emit("| ---- | ---- | ---- | ---- | ---- |")
                self.emit(*property_rows(schema))
                self.blank()


def generate(contract_path: Path) -> str:
    with contract_path.open("r", encoding="utf-8") as handle:
        contract = yaml.safe_load(handle)
    if not isinstance(contract, dict):
        raise SystemExit(f"contract {contract_path} is not a YAML mapping")
    return Renderer(contract).render()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Deterministically render docs/product/API_REFERENCE.md from"
            " the tenant control plane OpenAPI contract."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "regenerate to memory and fail (exit 1) when the committed"
            " reference differs from the contract-derived content"
        ),
    )
    args = parser.parse_args(argv)

    contract_path = REPO_ROOT / CONTRACT_RELPATH
    output_path = REPO_ROOT / OUTPUT_RELPATH
    rendered = generate(contract_path)

    if args.check:
        if not output_path.exists():
            print(
                f"FAIL: {OUTPUT_RELPATH} is missing; run"
                " scripts/dev/generate_api_reference.py",
                file=sys.stderr,
            )
            return 1
        current = output_path.read_text(encoding="utf-8")
        if current != rendered:
            print(
                f"FAIL: {OUTPUT_RELPATH} differs from the content generated"
                f" from {CONTRACT_RELPATH}. Hand edits are a validation"
                " failure (TR-26): edit the contract, then re-run"
                " scripts/dev/generate_api_reference.py.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {OUTPUT_RELPATH} matches {CONTRACT_RELPATH}")
        return 0

    output_path.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT_RELPATH} from {CONTRACT_RELPATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
